### ISSUE TITLE
step 1. Add tasks

### ISSUE THREAD

**Issue by kersov** [Maxrozvora/js-mentor#1]
Реалізувати можливість додавання таски в туду ліст

**Comment by Maxrozvora** [comment]
У об'єкта таска мають бути такі властивості як:
text, - вміст
completed: false, - стан виповнення
date, - дата створення
id - ідентифікатор

**Comment by Maxrozvora** [comment]
Перевір. зробив

**Comment by kersov** [comment]
@Maxrozvora передивись будь-ласка мої коменти
