### ISSUE TITLE
step 3. sort tasks

### ISSUE THREAD

**Issue by kersov** [Maxrozvora/js-mentor#6]

**Comment by kersov** [comment]
Зроби сортування по даті, виконано чи ні, імені. З меншого до більшого і навпаки.
Це має бути одна функція яка приймає масив і метод сортування і повертає відсортований масив. Тобі потрібно використати методи масивів для сортування.
По дефолту вище знаходяться таски які потрібно раніше виконати. При додаванні таска сортування збивається на дефолтне.
Змінювати сортування можна через дропдаун.

**Comment by Maxrozvora** [comment]
Виникла сложність. Як відсортувати по даті, коли вона у мене у форматі строки. Требуло її спочатку  числом зробити, як тоді на нього перетворити, або як зразу добавити числом. Чи може є якись інший спосіб?

**Comment by kersov** [comment]
Коли ти записуєш date в об*єкт:
let date = e.target.elements.dueDate.value;
я спочатку подумав що при такому записі ми отрамаємо об*єкт Date а виходить що ні.
тому записуй його не як строку а як Date
let date = new Date(e.target.elements.dueDate.value);
тоді зи зможеш легко порівнювати дати

**Comment by Maxrozvora** [comment]
Наступна проблема. Получається у мене спершу дані у такому форматі:
{"todos":
[
{"text":"go to shop","completed":false,"date":"23.01.2019","id":"4frjs5naqmu"},
{"text":"go to gym","completed":false,"date":"31.01.2019","id":"7l380yto28"}
]
}
такий формат потрібен для mustache.
так я роблю добавлення таска
todos.todos.push(todo);
тут якось не гарно виходить.
Проблема в тому що коли я роблю фільтрацію данні мені вертаються у такому вигляді:
[
{"text":"go to shop","completed":false,"date":"23.01.2019","id":"4frjs5naqmu"},
{"text":"go to gym","completed":false,"date":"31.01.2019","id":"7l380yto28"}
]
Як мені зробити щоб формат був однаковий?
https://github.com/Maxrozvora/js-mentor/tree/issues/3

**Comment by kersov** [comment]
Значить зробимо так:

1. почистити всі дані які зараз є;
2. при створенні todo об*єкта ми створємо об*єкт через конструктор (https://learn.javascript.ru/prototypes)
Структура об*єкта буда така ж сама тільки буде ще один метод 
getDate: function() {return this.date.toDateString()}
3. date має бути об*єктом типу Date 
let date = new Date(e.target.elements.dueDate.value);
4. в mustache будемо передавати {{getDate}}
5. Сортування буде відбуватись по атрибутах Date

**Comment by Maxrozvora** [comment]
Зробив сортіровку по даті, але як поміняти порядок? Хотів зробити це гарно, множучи результат метода sort на -1, але чомусь не виходить. Як можна це реалізувати, так щоб було гарно?)))
Ось мій код:
 const order = -1;
    switch (sortMethod) {
        case 'date':
             const sort = todos.todos.sort((a, b) => {
                 const dateA = new Date(a.date);
                 const dateB = new Date(b.date);
                 console.log((dateB - dateA) * order); // TODO console.log
                return (dateA - dateB) * order;
            });
            const todosSort = {
                todos: sort
            };
            return todosSort;
https://github.com/Maxrozvora/js-mentor/tree/issues/3

**Comment by kersov** [comment]
1. Навіщо такий запис?
`const dateA = new Date(a.date);`
a.date і так має бути датою

2. функцію сортування можна попробувати зробити так:
`return Math.sign(dateA - dateB) * order`

**Comment by Maxrozvora** [comment]
Навіщо такий запис? const dateA = new Date(a.date); a.date і так має бути датою.
Відповідь: тому що з локалсторежда не вертає об'єкт, а строку

**Comment by Maxrozvora** [comment]
Зробив сортування, але не знаю як міняти порядок.
Це не працює `return Math.sign(dateA - dateB) * order.`
Не підкажеш спосіб?
Зробив пул реквест, подивися, може щось треба підправити)

**Comment by kersov** [comment]
![66](https://user-images.githubusercontent.com/4148133/52198084-605f1800-286a-11e9-8f3b-b93f0e15840e.PNG)
В мене працює

**Comment by kersov** [comment]
@Maxrozvora додав коменти в ПР. видно?

**Comment by Maxrozvora** [comment]
@kersov видно

**Comment by kersov** [comment]
Залишилось пару невеличких змін і я мержу.
Потім - https://github.com/Maxrozvora/js-mentor/issues/8
